{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.security",
    "module": "spring-security-test",
    "version": "6.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-6.4.4.jar",
          "url": "spring-security-test-6.4.4.jar",
          "size": 132268,
          "sha512": "15e655371138a76a3298d89467dcd7be35b81fc7fbe2b2a21274bd7e5dc1d7b59f9e77d6f6a9f9ff59c2db92ac57139f5983a192d3ecd9e3ad7ea61d7a615d57",
          "sha256": "c7ff2e42c6b68edb44c8d816cdbfc5d5f2ba1db30e3abbd2c1a5ca43402057c8",
          "sha1": "33f679d83e8f345417327c65e0f22d2b9155c23d",
          "md5": "45f40fefbb81435e4d28b82d5f6c51f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.security",
          "module": "spring-security-core",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework.security",
          "module": "spring-security-web",
          "version": {
            "requires": "6.4.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.2.4"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-test",
          "version": {
            "requires": "6.2.4"
          }
        }
      ],
      "files": [
        {
          "name": "spring-security-test-6.4.4.jar",
          "url": "spring-security-test-6.4.4.jar",
          "size": 132268,
          "sha512": "15e655371138a76a3298d89467dcd7be35b81fc7fbe2b2a21274bd7e5dc1d7b59f9e77d6f6a9f9ff59c2db92ac57139f5983a192d3ecd9e3ad7ea61d7a615d57",
          "sha256": "c7ff2e42c6b68edb44c8d816cdbfc5d5f2ba1db30e3abbd2c1a5ca43402057c8",
          "sha1": "33f679d83e8f345417327c65e0f22d2b9155c23d",
          "md5": "45f40fefbb81435e4d28b82d5f6c51f7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-6.4.4-javadoc.jar",
          "url": "spring-security-test-6.4.4-javadoc.jar",
          "size": 232751,
          "sha512": "0cd5f98c51bcc13e39d90619b4098994c692ec64e78e5c0150631368ef7c3103691023565269476f79b91efe8cc8f4f8b6d227f3631e7819fc2400302cdc6987",
          "sha256": "23cdb59fca5cc49210c6f4fae2d42fb9004275d1e000dc1d1f1e7a9ff4219696",
          "sha1": "90a065189ace690c4e9146a76dab4b9e4f794fe8",
          "md5": "89dd3fa6c738bc6e2c17b5b92fd8564a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-security-test-6.4.4-sources.jar",
          "url": "spring-security-test-6.4.4-sources.jar",
          "size": 56485,
          "sha512": "7b5e341299d31a1ed1ff7a22c9b5038f59037d2dcd38a40d587c4a1f3aaa3e8920c5448d08f56201fda3ce584fdae16b2c0a34183694321c98009174d0dce646",
          "sha256": "44d71603f56bfd0417cb480010631b33e9daec828d451d1f45b37b117db1c0c8",
          "sha1": "738f73768560ae78158d9c063fe54e8bf903f922",
          "md5": "14d74ad987cadc5da974931667fdc582"
        }
      ]
    }
  ]
}
